# Generated by Django 4.1.5 on 2023-02-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dfggfgg', upload_to='images'),
            preserve_default=False,
        ),
    ]
